name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create credentials file
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode > $GITHUB_WORKSPACE/credentials.json

      - name: Test if GOOGLE_APPLICATION_CREDENTIALS is set correctly
        run: |
          if [ -z "${GITHUB_WORKSPACE}/credentials.json" ]; then
            echo "GOOGLE_APPLICATION_CREDENTIALS is not set."
            exit 1
          elif [ ! -f "${GITHUB_WORKSPACE}/credentials.json" ]; then
            echo "GOOGLE_APPLICATION_CREDENTIALS file does not exist at ${GITHUB_WORKSPACE}/credentials.json."
            exit 1
          else
            echo "GOOGLE_APPLICATION_CREDENTIALS is set and the file exists at ${GITHUB_WORKSPACE}/credentials.json."
          fi
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/credentials.json

      - name: Run Streamlit
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/credentials.json
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
          ls -l $GOOGLE_APPLICATION_CREDENTIALS
          streamlit run Streamlit-sellersdata.py
